package pe.edu.sistemas.sismanweb.domain;
// Generated 31/08/2017 12:03:58 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.CascadeType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Alumno generated by hbm2java
 */
@Entity
@Table(name = "alumno", catalog = "modelogeneralfisi")
public class Alumno implements java.io.Serializable {

	private Integer idAlumno;
	private Persona persona;
	private Plan plan;
	private TipoAlumno tipoAlumno;
	private int alumnoActivo;

	public Alumno() {
	}

	public Alumno(Persona persona, Plan plan, TipoAlumno tipoAlumno, int alumnoActivo) {
		this.persona = persona;
		this.plan = plan;
		this.tipoAlumno = tipoAlumno;
		this.alumnoActivo = alumnoActivo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_ALUMNO", unique = true, nullable = false)
	public Integer getIdAlumno() {
		return this.idAlumno;
	}

	public void setIdAlumno(Integer idAlumno) {
		this.idAlumno = idAlumno;
	}

	@ManyToOne(fetch = FetchType.LAZY, cascade=CascadeType.ALL)
	@JoinColumn(name = "PERSONA_ID_PERSONA", nullable = false)
	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PLAN_IDPLAN", nullable = false)
	public Plan getPlan() {
		return this.plan;
	}

	public void setPlan(Plan plan) {
		this.plan = plan;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TIPO_ALUMNO_IDTIPO_ALUMNO", nullable = false)
	public TipoAlumno getTipoAlumno() {
		return this.tipoAlumno;
	}

	public void setTipoAlumno(TipoAlumno tipoAlumno) {
		this.tipoAlumno = tipoAlumno;
	}

	@Column(name = "ALUMNO_ACTIVO", nullable = false)
	public int getAlumnoActivo() {
		return this.alumnoActivo;
	}

	public void setAlumnoActivo(int alumnoActivo) {
		this.alumnoActivo = alumnoActivo;
	}

}
