package pe.edu.sistemas.sismanweb.domain;
// Generated 31/08/2017 12:03:58 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CategoriaDocente generated by hbm2java
 */
@Entity
@Table(name = "categoria_docente", catalog = "modelogeneralfisi")
public class CategoriaDocente implements java.io.Serializable {

	private Short idecategoriaDocente;
	private String categoriaDocenteNombre;
	private Set<Docente> docentes = new HashSet<Docente>(0);

	public CategoriaDocente() {
	}

	public CategoriaDocente(String categoriaDocenteNombre) {
		this.categoriaDocenteNombre = categoriaDocenteNombre;
	}

	public CategoriaDocente(String categoriaDocenteNombre, Set<Docente> docentes) {
		this.categoriaDocenteNombre = categoriaDocenteNombre;
		this.docentes = docentes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "IDECATEGORIA_DOCENTE", unique = true, nullable = false)
	public Short getIdecategoriaDocente() {
		return this.idecategoriaDocente;
	}

	public void setIdecategoriaDocente(Short idecategoriaDocente) {
		this.idecategoriaDocente = idecategoriaDocente;
	}

	@Column(name = "CATEGORIA_DOCENTE_NOMBRE", nullable = false, length = 30)
	public String getCategoriaDocenteNombre() {
		return this.categoriaDocenteNombre;
	}

	public void setCategoriaDocenteNombre(String categoriaDocenteNombre) {
		this.categoriaDocenteNombre = categoriaDocenteNombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categoriaDocente")
	public Set<Docente> getDocentes() {
		return this.docentes;
	}

	public void setDocentes(Set<Docente> docentes) {
		this.docentes = docentes;
	}

}
