package pe.edu.sistemas.sismanweb.domain;
// Generated 31/08/2017 12:03:58 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Plan generated by hbm2java
 */
@Entity
@Table(name = "plan", catalog = "modelogeneralfisi")
public class Plan implements java.io.Serializable {

	private Integer idplan;
	private int escuelaIdescuela;
	private String planNombre;
	private Set<Alumno> alumnos = new HashSet<Alumno>(0);
	private Set<CursoBase> cursoBases = new HashSet<CursoBase>(0);

	public Plan() {
	}

	public Plan(int escuelaIdescuela, String planNombre) {
		this.escuelaIdescuela = escuelaIdescuela;
		this.planNombre = planNombre;
	}

	public Plan(int escuelaIdescuela, String planNombre, Set<Alumno> alumnos, Set<CursoBase> cursoBases) {
		this.escuelaIdescuela = escuelaIdescuela;
		this.planNombre = planNombre;
		this.alumnos = alumnos;
		this.cursoBases = cursoBases;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "IDPLAN", unique = true, nullable = false)
	public Integer getIdplan() {
		return this.idplan;
	}

	public void setIdplan(Integer idplan) {
		this.idplan = idplan;
	}

	@Column(name = "ESCUELA_IDESCUELA", nullable = false)
	public int getEscuelaIdescuela() {
		return this.escuelaIdescuela;
	}

	public void setEscuelaIdescuela(int escuelaIdescuela) {
		this.escuelaIdescuela = escuelaIdescuela;
	}

	@Column(name = "PLAN_NOMBRE", nullable = false, length = 45)
	public String getPlanNombre() {
		return this.planNombre;
	}

	public void setPlanNombre(String planNombre) {
		this.planNombre = planNombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "plan")
	public Set<Alumno> getAlumnos() {
		return this.alumnos;
	}

	public void setAlumnos(Set<Alumno> alumnos) {
		this.alumnos = alumnos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "plan")
	public Set<CursoBase> getCursoBases() {
		return this.cursoBases;
	}

	public void setCursoBases(Set<CursoBase> cursoBases) {
		this.cursoBases = cursoBases;
	}

}
